### PR TITLE
Dockerize App

### PR DESCRIPTION
**Pull request by ciremoussadia**
Dockerize app in preparation to deploys it in k8s cluster.

### CODE REVIEW

**Comment by llambeau** [comment]
It would be nice to check if we can use multistage builds to avoid shipping the final docker image with build-essentials.

**Comment by ciremoussadia** [comment]
Ok @llambeau

**Comment by blambeau** [comment]
Ok for me so far, I agree with @llambeau about multi-stage.

Also we need to decide whether we put the q8s files here (public) or if we keep them elsewhere. You probably need to pair-program on that in practice.

E.g. Louis does the q8s-isation here, to be replicated by Cire on try-alf?

**Comment by ciremoussadia** [comment]
@llambeau approved the multistage. Ok @blambeau I'll see with Louis the plan to the q8s-isation.

**Pull request merged**
